### ISSUE TITLE
adb需要更新

### ISSUE THREAD

**Issue by Cyl18** [wotermelon/toJump#1]
adb 太老了 对新版本 Android 不支持

**Comment by wotermelon** [comment]
@Cyl18 android什么版本

型号：小米mix2
android版本：MIUI9(android 7)

亲测没问题

**Comment by zhangruinian** [comment]
不行呀 adb需要额外设置么
小米6 miui9 @wotermelon

**Comment by zhangruinian** [comment]
额外升级了adb可以出现了 @wotermelon

**Comment by leegsen7** [comment]
你的是报device not found这个错吗

**Comment by wotermelon** [comment]
@leegsen7 可以用助手之类的装驱动

**Comment by leegsen7** [comment]
@wotermelon 我也升级了一下adb，可以正常跑起来了。

**Comment by wotermelon** [comment]
adb工具已经升级到最新。
