### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhanghaifeng213** [wotermelon/toJump#10]
![image](https://user-images.githubusercontent.com/26516275/34951296-b536d7bc-fa50-11e7-932f-60c956e0d40f.png)

**Comment by zhanghaifeng213** [comment]
Administrator@USER-20160901LV MINGW64 /e/作业/作业/作业完成情况/node/wx_tyt/toJu                                                                                        mp-master
$ npm start

> toJump@1.0.0 start E:\作业\作业\作业完成情况\node\wx_tyt\toJump-master
> node app.js

>>  Listening on port 4000
页面已连接...
页面已连接...
(node:4204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                                                                        tion id: 1): Error: Command failed: E:\作业\作业\作业完成情况\node\wx_tyt\toJump                                                                                        -master\lib\win\adb.exe shell screencap -p /sdcard/screenshot.png
adb server version (31) doesn't match this client (39); killing...
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon

**Comment by zhanghaifeng213** [comment]
这个报错是什么原因造成的呢？

**Comment by wotermelon** [comment]
@zhanghaifeng213 #9
